# Generated by Django 4.1.2 on 2022-10-18 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=32)),
                ('contact_type', models.PositiveSmallIntegerField()),
                ('massage_text', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('date_of_crate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecretNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_name', models.CharField(max_length=32)),
                ('note_text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='password_manager_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='LoginDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_date_name', models.CharField(max_length=32)),
                ('login_name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=64, null=True)),
                ('login_date_group', models.PositiveSmallIntegerField(choices=[(1, 'Web Application Password'), (2, 'Mail Account'), (3, 'Online Identies'), (4, 'Social Networks'), (5, 'Financial Record'), (6, 'Desktop App'), (7, 'Mobie App')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='password_manager_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(unique=True)),
                ('expiration_date', models.DateField()),
                ('card_type', models.PositiveSmallIntegerField(choices=[(1, 'Visa'), (2, 'MasterCard'), (3, 'AmericanExpress'), (4, 'Discover')])),
                ('cvv', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='password_manager_app.user')),
            ],
        ),
    ]
