# Generated by Django 4.1.2 on 2022-10-26 18:29

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager_app', '0002_alter_logindate_options_alter_secretnote_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretnote',
            name='note_text',
            field=fernet_fields.fields.EncryptedTextField(),
        ),
    ]
