# Generated by Django 4.1.2 on 2022-10-27 17:03

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager_app', '0005_alter_secretnote_note_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_number',
            field=encrypted_model_fields.fields.EncryptedCharField(unique=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='cvv',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
