# Generated by Django 4.1.2 on 2022-10-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager_app', '0006_alter_creditcard_card_number_alter_creditcard_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_number',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
