# Generated by Django 4.1.2 on 2022-10-27 18:10

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager_app', '0007_alter_creditcard_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindate',
            name='password',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='logindate',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=64),
            preserve_default=False,
        ),
    ]
