# Generated by Django 4.1.2 on 2022-10-31 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager_app', '0008_alter_logindate_password_alter_logindate_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoginDate',
            new_name='LoginData',
        ),
        migrations.AlterModelOptions(
            name='logindata',
            options={'ordering': ['data_name']},
        ),
        migrations.RenameField(
            model_name='logindata',
            old_name='date_name',
            new_name='data_name',
        ),
        migrations.RenameField(
            model_name='logindata',
            old_name='login_date_group',
            new_name='login_data_group',
        ),
    ]
