# Generated by Django 4.1.2 on 2022-10-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager_app', '0009_rename_logindate_logindata_alter_logindata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindata',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
