# Generated by Django 4.1.2 on 2022-11-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager_app', '0010_logindata_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportcontact',
            name='case_topic',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
