# Generated by Django 4.1.2 on 2022-11-01 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager_app', '0011_supportcontact_case_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportcontact',
            old_name='massage_text',
            new_name='message_text',
        ),
    ]
