# Generated by Django 4.1.2 on 2022-11-01 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager_app', '0012_rename_massage_text_supportcontact_message_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportcontact',
            old_name='case_topic',
            new_name='topic',
        ),
    ]
