# Generated by Django 4.1.2 on 2022-11-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager_app', '0016_alter_logindata_login_data_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportcontact',
            name='contact_type',
        ),
    ]
