# Generated by Django 4.1.2 on 2022-11-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager_app', '0017_remove_supportcontact_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_type',
            field=models.CharField(choices=[('Visa', 'Visa'), ('MasterCard', 'MasterCard'), ('AmericanExpress', 'AmericanExpress'), ('Discover', 'Discover')], max_length=32),
        ),
    ]
